### PR TITLE
Make the extension look like vscode

### PR DESCRIPTION
**Pull request by samfundev**
To make the extension look like vscode, I used [vscode-elements](https://vscode-elements.github.io/) and some css changes. I also made a few other changes to generally make the UI look better.

Dark Modern:
image

Light Modern:
image

### CODE REVIEW

**Comment by phil294** [comment]
Judging from the screenshots, this looks awesome! Getting actual light theme support is exciting.

Will have to have a closer look.

**Comment by markcarroll** [comment]
This looks great. Can we fix the context menu too? My current patch does this:

```css
ul.context-menu-wrapper {
  background: var(--vscode-menu-background);
}
ul.context-menu-wrapper > li {
  padding: 8px 20px;
}
ul.context-menu-wrapper > li:hover {
  background-color: var(--vscode-menu-selectionBackground, var(--vscode-menu-background));
  color: var(--vscode-menu-selectionForeground, var(--vscode-menu-foreground));
}
```

**Comment by phil294** [comment]
This is an excellent PR. As you have probably noticed, all my CSS so far hasn't been very structured so far and needs rigorous cleanup / better tooling. Your changes look great both in code and UI. Also love moving the padding from the container into the commit rows, the commit selection styles and so on. So many improvements!

There's a few fixes that needed being done, e.g. the git action buttons  weren't clickable anymore and checkboxes were not responsive. I was under the wrong impression to have push permissions to your branch, so I fixed these things myself, but can't push now... instead, I'll merge this into master and then add the fix commits on top afterwards. Hope this is fine for you - I probably should have left comments in your code instead.

I think ref-tip (branches) background also needs adjustments, it's too dark in light mode and a bit too bright in dark theme now IMO, depending on the theme it's the same as the background. Maybe it can be theme-dependent too.

Also the buttons lack haptic feedback when you click them now (i.e. adding styles for `:active` pseudo class), making them all feel as if they were permanently disabled. Just like normal VSCode buttons (what a horrible trend IMO) but I'd like to change that again. Not really problematic though as everything important has a greyed out animation/disable state while it's processing so the user immediately gets feedback on click.

**Comment by phil294** [comment]
@markcarroll 

before:
image

with your changes:

image

I like the improved theme integration and added it (thanks!), but the padding looks out of place to me. I know that some people like huge ass paddings though (for whatever reason), so I think at some point it would be good to have a general setting to inflate the padding around various elements by factor X. Maybe prompt the user to choose / select what they like best. Doesn't have any priority for me though so that would probably be best put into a new issue.

**Comment by samfundev** [comment]
@phil294 I really appreciate the kind words! I tried to make some improvements as I was working and I should have documented them better, but I'm glad you liked them. Apologizes, I don't know how the push access got disabled. I thought that was usually on by default. Since vscode-elements has a context menu element, I could do a follow up PR to fix that.

**Comment by phil294** [comment]
Unfortunately, I'll have to revert 77a452ec1461b3c4b40bc6f470e380cfd36ead71, in particular the change from native controls to vscode-elements. There are simply too many problems with it. The accessibility with most of them is broken, it's full of bugs and it's the main thing I'm fighting against when developing. It also bloats up the bundle and comes with little advantages. Here's a more detailed list: https://github.com/vscode-elements/elements/issues/448

Instead, I'll go back to normal html controls and we'll need to add some css improvements here and there. This means the extension will look worse again with next update.

**Comment by phil294** [comment]
Also I'm of the opinion that vscode-elements shouldn't be an actual javascript library with custom elements. This should just be a stylesheet. It's a graet example of overengineering with bad outcome.

**Comment by samfundev** [comment]
@phil294 I'd be willing to help with the effort. It seems like the lite version might be a good starting point, but I just want to make sure I understand what's wrong with it. I assume by "custom dom elements" you're referring to the additional elements that are required for the checkbox component?

**Pull request merged**
